# example values
indexing-settings:
  sites:
    - url: https://www.skillbox.ru
      name: skillbox.ru
    - url: https://www.playback.ru
      name: playBack.ru
    - url: https://upakmarket.com
      name: upakmarket.com

server:
  port: 8081

spring:
  datasource:
    username: roma2
    password: roma2
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      SET: FOREIGN_KEY_CHECKS=0;
      ddl-auto: create
    show-sql: true




#server:
#  servlet:
#    context-path: /admin


#logging:
#  level:
#    org.springframework.web:  FINEST
#    org.apache:  FINEST
#    org.hibernate:  FINEST