# example values
indexing-settings:
  sites:
    - url: https://www.skillbox.ru
      name: skillbox.ru
    - url: https://www.playback.ru
      name: playBack.ru
    - url: https://fparf.ru
      name: fparf.ru



spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create-drop # Эта строка удаляет и пересоздает схему при каждом запуске
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: search
    password: search
    hikari:
      schema: app_schema
      connection-init-sql: create schema if not exists app_schema
      connection-timeout: 10000
      show-sql: true



#server:
#  servlet:
#    context-path: /admin


#logging:
#  level:
#    org.springframework.web:  FINEST
#    org.apache:  FINEST
#    org.hibernate:  FINEST